# User config
author: "이이에에."
tagline: "p5.js, javascript coding"
description: "We believe that you can do beautiful coding based on 4th industry education. Whoever, wherever, whatever."
keywords: "Heart keep going on 2021, Irregular"
email: "iiee@naver.com"
linkedin: "https://www.linkedin.com/"
instagram: "https://instagram.com/"
github: "https://github.com/iiee0"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
