# User config
author: "이이에에."
tagline: "이이에에 tag"
description: "Let's create ∞ Let's make"
keywords: "Heart keep going on 2021, Irregular"
email: "iiee@naver.com"
linkedin: "https://www.linkedin.com/"
instagram: "https://instagram.com/"
github: "https://github.com/iiee0"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
